# Generated by Django 3.2.5 on 2023-02-12 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='related_project',
        ),
    ]
