# Generated by Django 3.2.5 on 2023-02-12 17:06

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_related_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects_by_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to=app.models.upload_path)),
                ('name', models.TextField()),
                ('desc', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.aiesec_projects')),
            ],
        ),
    ]
