# Generated by Django 3.2.5 on 2023-01-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='fq',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
